#!/bin/bash

###############################################################################
# Uses python scripts written by Jakob to combine hdf5 files                  #
# merge.py: combines two or more files with the same cols, different events   #
# mix.py:   combines two or more files with the same events, different cols   #
###############################################################################

prefix="/data/user/zgriffith/ShowerLLH/IT81_sim/files"
I3="/home/zgriffith/icetray/V13_03/build"
simList="11644"

for sim in ${simList}; do
  fileList="${prefix}/Raw_${sim}_*.hdf5"
  outfile="${prefix}/Raw_${sim}.hdf5"
  python "${I3}/hdfwriter/resources/scripts/merge.py" "-o" "$outfile" $fileList
  #python "${I3}/hdfwriter/resources/scripts/mix.py" "${prefix}/SimLLH_${sim}.hdf5" "${prefix}/SimLLH_${sim}.hdf5"
done
