#!/bin/bash

###############################################################################
# This script runs the grid search method on all of simulation
###############################################################################

cd "/home/zgriffith/ShowerLLH/npx4"
prefix="/home/zgriffith/ShowerLLH/run_sim"

config="IT81"


s_prefix="/data/sim/IceTop/2011/filtered/CORSIKA-ice-top/level2/10687"
groupList="${s_prefix}/*"
for group in $groupList; do
  group=${group:(-11):11}
  #./submit_npx4.sh env-shell.sh python "$prefix/GetMC.py" $config $sim $group
  #./submit_npx4.sh /net/user/fmcnally/offline/V04-02-00/build/env-shell.sh python "${prefix}/MakeLLHFiles.py" $config $sim $group 
  ./submit_npx4.sh /net/user/santander/icecube/icetray/V04-02-00/build/env-shell.sh python "${prefix}/MakeLLHFiles_gammas.py" $config $sim $group 
done


cd ..
