#!/bin/bash

###############################################################################
# This script runs the grid search method on all of simulation
###############################################################################

cd "/home/zgriffith/ShowerLLH/npx4"
prefix="/home/zgriffith/ShowerLLH/run_sim"

config="IT73"
echo -n "Proton, Helium, Oxygen, or Iron? [P|He|O|Fe|G]: "
read comp

if [ $comp == "G" ]; then
  simList="9551"
elif [ $comp == "P" ]; then
  #simList="7006 7351 7579"
  simList="7006"
elif [ $comp == "He" ]; then
  simList="7483 7241 7263 7791"
elif [ $comp == "O" ]; then
  simList="7486 7242 7262 7851"
elif [ $comp == "Fe" ]; then
  simList="7394 7007 7784"
fi

for sim in $simList; do
  s_prefix="/data/sim/IceTop/2010/filtered/level2a/CORSIKA-ice-top/${sim}"
  groupList="${s_prefix}/*"
  for group in $groupList; do
    group=${group:(-11):11}
    #./submit_npx4.sh env-shell.sh python "$prefix/GetMC.py" $config $sim $group
    #./submit_npx4.sh /net/user/fmcnally/offline/V04-02-00/build/env-shell.sh python "${prefix}/MakeLLHFiles.py" $config $sim $group 
    ./submit_npx4.sh /net/user/santander/icecube/icetray/V04-02-00/build/env-shell.sh python "${prefix}/MakeLLHFiles.py" $config $sim $group 
  done
done

cd ..
